export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  odooUrl: process.env.ODOO_URL ?? "",
  odooUsername: process.env.ODOO_USERNAME ?? "",
  odooPassword: process.env.ODOO_PASSWORD ?? "",
  odooDatabase: process.env.ODOO_DATABASE ?? "",
  odooTeamId: process.env.ODOO_TEAM_ID ?? "",
  odooTeamName: process.env.ODOO_TEAM_NAME ?? "",
  odooLeadType: process.env.ODOO_LEAD_TYPE ?? "",
  odooUserId: process.env.ODOO_USER_ID ?? "",
  odooUserName: process.env.ODOO_USER_NAME ?? "",
  odooUserLogin: process.env.ODOO_USER_LOGIN ?? "",
};
